# 🚀 DESPLIEGUE CHATGPT PROXY SERVER
# Para aprovechar tu suscripción ChatGPT Plus ($20/mes)

version: "3.8"

services:
  chatgpt-proxy:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - CHATGPT_RATE_LIMIT=20
      - CHATGPT_RATE_WINDOW=60000
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}  # Opcional, para fallback
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Redis para caching avanzado (opcional)
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M

  # Nginx como reverse proxy (producción)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl/certs
    depends_on:
      - chatgpt-proxy
    restart: unless-stopped

volumes:
  redis_data:

networks:
  default:
    name: chatgpt-proxy-network
